---
name: icemaze
version: '0.1'
summary: A sliding block adventure.
description: |
  IceMaze is puzzle game.

  You play a block moving on the ice. Each time you move, you are forced to
  slide until a wall stops you. Reaching the finish position will not be easy.

  Contains:
    - About twenty levels and various blocks (locks, corner, wormhole,…)
    - A level generator.
icon: "./resources/intro_screen.png"
grade: stable
confinement: strict
base: core18
apps:
  icemaze:
    command: desktop-launch ${SNAP}/bin/icemaze
    plugs:
    - audio-playback
    - opengl
    - x11
    - pulseaudio
parts:
  cmake:
    source: https://github.com/Kitware/CMake
    source-type: git
    source-depth: 1
    plugin: cmake
    override-build: |
      mkdir -p build
      cd build
      cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_STAGE/cmake \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install
    build-packages:
    - build-essential
    - libssl-dev
    - libncurses5-dev
    stage-packages:
    - libssl1.1
    - libncurses5
    - libtinfo5
    prime: []
  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin
  icemaze:
    after:
    - cmake
    - desktop-glib-only
    plugin: cmake
    source: https://github.com/ArthurSonzogni/icemaze
    source-type: git
    source-depth: 1
    stage-packages:
    - libgl1-mesa-glx
    - libpulse0
    build-packages:
    - libglu-dev
    - libpulse-dev
    - xorg-dev
    override-build: |
      $SNAPCRAFT_STAGE/cmake/bin/cmake \
        -DCMAKE_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL \
        -DCMAKE_BUILD_TYPE=RelWithDebInfo \
        $SNAPCRAFT_PART_SRC
      make -j ${SNAPCRAFT_PARALLEL_BUILD_COUNT}
      make install
passthrough:
  title: icemaze
  license: MIT
