name: icemaze
adopt-info: icemaze
summary: A sliding block adventure.
description: |
  IceMaze is puzzle game.

  You play a block moving on the ice. Each time you move, you are forced to
  slide until a wall stops you. Reaching the finish position will not be easy.

  Contains:
    - About twenty levels and various blocks (locks, corner, wormhole,…)
    - A level generator.

icon: "./resources/intro_screen.png"
grade: stable
confinement: strict
base: core20

apps:
  icemaze:
    command: bin/desktop-launch $SNAP/usr/bin/icemaze
    plugs:
      - audio-playback
      - opengl
      - x11
      - pulseaudio

parts:
  desktop-glib-only:
    plugin: make
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    build-packages:
    - libglib2.0-dev
    stage-packages:
    - libglib2.0-bin

  icemaze:
    after:
    - desktop-glib-only
    plugin: cmake
    source: https://github.com/ArthurSonzogni/icemaze
    source-type: git
    stage-packages:
      - libgl1-mesa-glx
      - libopengl0
      - libpulse0
    build-packages:
      - libglu1-mesa-dev
      - libpulse-dev
      - xorg-dev
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version $(git rev-list --count HEAD)
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release

passthrough:
  title: icemaze
  license: MIT
